### ISSUE TITLE
Should I tag my landing pages? If so, how?

### ISSUE THREAD

**Issue by mridang** [Nosto/docs-nosto-com#1]

**Comment by ValterAndersson** [comment]
I don't think this comes up that often with direct implementations and is pretty useless extension anyway. Your thoughts @mridang ?

**Comment by mridang** [comment]
Maybe we could just ask them to tag it as "other"

**Comment by ValterAndersson** [comment]
You mean `page type: other` basically ?

**Comment by mridang** [comment]
Correct
