### ISSUE TITLE
Add subtitles to code examples

### ISSUE THREAD

**Issue by ValterAndersson** [Nosto/docs-nosto-com#15]
In "Product Tagging" perhaps we need a subtitle to seperate out the first bit (absolute MVP) the next section including brand custom fields etc

**Comment by mridang** [comment]
I agree. Maybe "Basic Tagging" and "Extended Tagging"?

**Comment by ValterAndersson** [comment]
Done. Added subtitles `Basic tagging` and `Tagging attribute extension`
