### ISSUE TITLE
Can you provide an example of how to fetch custom fields in templates?

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#18]
So far, we only have examples of of product.getCustomFields('key') in Slack but nowhere in our documentation. That might be added here:
https://github.com/Nosto/docs-nosto-com/wiki/Product-Tagging#tagging-the-tags-andor-custom-fields

**Comment by KonstantinDerEntwirrer** [comment]
**When tagging is**
```
  <span class="custom_fields">
  <span class="material">Cotton</span>
  <span class="weather">Summer</span>
```
**variable would be** 
$product.getCustomField('material')
$product.getCustomField('weather')

**Output would be**
Cotton
Summer

**Comment by ValterAndersson** [comment]
Currently we don't cover templating at all in this repository, but we need another place to cover these topics definitely. Will bring this topic up.
