### ISSUE TITLE
Order tagging after GDPR with mininum personal data

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#20]
How does order tagging look like, if the merchant has reduced the customer tagging to the minimum and removed first and last name?

See class "buyer" here and please show an alternate example.
https://github.com/Nosto/docs-nosto-com/wiki/Order-Tagging

**Comment by ValterAndersson** [comment]
Don't you think the section "Tagging the buyer" under the example already explains concisely that you can omit either parts or the buyer section completely? 

Tagging the buyer
You can omit the buyer tagging either partially, or completely if you do not want Nosto to crawl this information. The user details are stored for possible marketing purposes and mainly observed email address is used in this context. Marketing permission is false by default but if this user has explicitly agreed to receive marketing then you can set it to true manually.

**Comment by StanislavKraus** [comment]
Reading is helpful. 
Thanks, Valter! I didn't see that section exists already.

Solved.
