### ISSUE TITLE
How to correctly send product IDs?

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#25]
Do you need to write
{
product_id: "12345",
product_id: "12346"
}

or is

{
"12345",
"12346"
}

enough?

here we write product_id: https://github.com/Nosto/docs-nosto-com/wiki/Updating-products-using-the-Products-API
here we dont: https://developer.nosto.com/?javascript#discontinue-product

**Comment by fairlane** [comment]
You need to use array (square brackets) and only the ids are enough. So basically this
```
[
"12345",
"12346"
]
```

**Comment by mridang** [comment]
@StanislavKraus this API https://developer.nosto.com/?javascript#discontinue-product is different and will be deprecated.
