### ISSUE TITLE
How do I programmatically send my cart contents?

### ISSUE THREAD

**Issue by mridang** [Nosto/docs-nosto-com#3]
When customers remove or change quantity of items in the cart, we reload the cart through AJAX. How can we call Nosto JS to reprocess new data that has arrived through AJAX reload?

**Comment by ValterAndersson** [comment]
Will need to write a article under https://github.com/Nosto/docs-nosto-com/wiki/Handling-dynamic-use-cases about handling dynamic carts that can be referenced from here https://github.com/Nosto/docs-nosto-com/wiki/Cart-Tagging

**Comment by ValterAndersson** [comment]
Wrote article: https://github.com/Nosto/docs-nosto-com/wiki/Dynamically-refreshing-Nosto-after-an-add-to-cart-event
