### ISSUE TITLE
VueJS usage changes

### ISSUE THREAD

**Issue by timowestnosto** [Nosto/docs-nosto-com#30]
A few change suggestions related to https://github.com/Nosto/docs-nosto-com/wiki/VueJS

* the global mixin that exposes Nosto methods is not really needed, since no instance state is used

* the nosto-slot usage has lots of duplicated markup content, try to optimize it

```
<nosto-slot nid="frontpage-nosto-1" inline-template>
          <div class="nosto_element no-inject" id="frontpage-nosto-1">
```

Could nosto-slot be a directive instead?

* get of inline-template usage and use slots instead

* should we add a component for customer tagging rendering?

**Comment by mridang** [comment]
@timowestnosto I don't think this is valid now that we have the SPA docs. Please reopen if you think otherwise.
