### ISSUE TITLE
Add documentation for search parameter tag

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#31]
When does Nosto suggest to tag the search parameter?
https://help.nosto.com/get-started/1st-steps/tagging-search-parameter

What was the use case, issue, or problem to go the extra mile and tag the search parameter instead or in addition to the have it in "Search Query Parameter" in Nosto's Settings section?

**Comment by mridang** [comment]
https://github.com/Nosto/docs-nosto-com/wiki/Search-Tagging
