### ISSUE TITLE
Add instructions how to use current tags filtering

### ISSUE THREAD

**Issue by fairlane** [Nosto/docs-nosto-com#34]
The tagging
`<span class="nosto_tag" style="display:none">My tag</span>`

The settings
<img width="917" alt="cursor_and_recommendations_-browsing_history_related" src="https://user-images.githubusercontent.com/15191701/49784921-71d2ea80-fd27-11e8-87f5-c90564ba467c.png">

**Comment by mridang** [comment]
https://github.com/Nosto/docs-nosto-com/wiki/Setting-up-dynamic-filtering
