### ISSUE TITLE
Documentation on AB testing under JS API

### ISSUE THREAD

**Issue by ValterAndersson** [Nosto/docs-nosto-com#39]
Today this article: https://help.nosto.com/recommendations/on-site-recommendations-ab-testing referrs to modifying the old embed script referred here: http://connect.nosto.com/tagging#add_embedscript, but we are actively using this in documentation https://github.com/Nosto/docs-nosto-com/wiki/Add-Nosto-script

**Comment by StanislavKraus** [comment]
I need it for a big client. Can you provide it?

**Comment by ValterAndersson** [comment]
Current workaround is to modify newer script (https://github.com/Nosto/docs-nosto-com/wiki/Add-Nosto-script) to the older version (http://connect.nosto.com/tagging#add_embedscript) and then follow the help article https://help.nosto.com/recommendations/on-site-recommendations-ab-testing. 

There are no drawbacks to this solution, and code needs to be modified anyway to set up the AB-testing, so essentially no extra work should be required.

**Comment by mridang** [comment]
That article isn't being updated as it belongs to Romain.
