### ISSUE TITLE
What is the customer-reference and how is it used?

### ISSUE THREAD

**Issue by mridang** [Nosto/docs-nosto-com#4]
How does it work, how should it be used, what's its purpose? Can a customer_reference parameter be used for identification of the user if the user doesn't want to provide email?

**Comment by ValterAndersson** [comment]
I removed this example for now since its a edge-case. I think its more confusing than helpful to have it in the documentation. Your thoughts @mridang ?

**Comment by mridang** [comment]
Good idea. Maybe we could add this as a section under "Manual Tagging - Advanced" as an article called "Supporting cross-device sessions"

**Comment by mridang** [comment]
https://help.nosto.com/get-started/1st-steps/tagging-customer-information

**Comment by ValterAndersson** [comment]
Added subsection: `Tagging customer reference (supporting cross-device sessions)` in this article https://github.com/Nosto/docs-nosto-com/wiki/Adding-the-customer-information
