### ISSUE TITLE
Add documentation, if the tagging isn't done or incomplete. What are the ramifications on Nosto's recommendation engine in such a case?

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#42]

**Comment by mridang** [comment]
Nosto wont work.

**Comment by StanislavKraus** [comment]
What about having only product ID tagged on every page type? Will we be able to create our _Product Graph_?

**Comment by mridang** [comment]
I've documented it here: https://github.com/Nosto/techdocs/wiki/Basic:-Minimum-Product-Tagging
