### ISSUE TITLE
Document SIOCP-related details

### ISSUE THREAD

**Issue by renat-nosto** [Nosto/docs-nosto-com#44]
### Js api
Current version is at [visit custom event at help.nosto.com](https://help.nosto.com/cscp/visit-custom-event) 
Please reflect the part that `addSegmentCodeToVisit` does not trigger `loadRecommendations` and `loadRecommendations` should be triggered explicitly if code was added dynamically (after initial `loadRecommendations` was executed)
### Segments in GA
It might be worth adding [segment information](https://help.nosto.com/cscp/why-am-i-seeing-nosto-specific-events-in-my-google-analytics-admin-panel) into [Google Analytics page](https://github.com/Nosto/techdocs/wiki/Tracking-Nosto-with-Google-Analytics)

**Comment by mridang** [comment]
I've added it here: https://github.com/Nosto/techdocs/wiki/Manually-Segmenting-Users Please reopen the issue if you think it is unclear.
