### ISSUE TITLE
Manual Tagging Section Missing

### ISSUE THREAD

**Issue by srjwebster** [Nosto/docs-nosto-com#45]
When visited it links back to start page. 

The link and text read https://github.com/Nosto/techdocs/wiki/Manully-Sending-Tagging

If you visit https://github.com/Nosto/techdocs/wiki/Manually-Sending-Tagging manually, the page loads, but only contains the letter "n".

**Comment by mridang** [comment]
@srjwebster I've fixed it now. That documentation link was a zombie. Thanks for reporting it. If your use-case isn't covered in the docs, do open an issue. Thanks.
