### ISSUE TITLE
Page Type other nostodebug tool

### ISSUE THREAD

**Issue by OZZlE** [Nosto/docs-nosto-com#47]
I am using the javascript API.

When I use the page type "other"

    <div class="nosto_page_type" style="display:none">other</div>

The debugtool doesn't understand it and simply says "No page type!"
![Skärmklipp 2019-05-09 10 01 16](https://user-images.githubusercontent.com/893783/57437169-83baaa00-7241-11e9-90d3-782988058077.png)

If I simply change it to 'product' then it shows that.. I have checked that the element is there when nosto is initialized and so on..

Also have you guys heard of CMS pages? :D

**Comment by OZZlE** [comment]
Is it because we have an older version of the Nosto plugin? I'm about doubtful about that though as I think this js is loaded directly from your server? Would still make sense if there was a CMS page type also I think..

**Comment by StanislavKraus** [comment]
I can imagine that it has to do with your plugin, it's ancient :-)
https://github.com/Nosto/nosto-magento/tree/2.6.7

Give it a try and have a look after upgrading. you can start doing so on a Nosto test account and your staging
The latest release is: https://github.com/Nosto/nosto-magento/tree/3.10.0

**Comment by mridang** [comment]
@OZZlE Sorry about that. I've updated it here: https://github.com/Nosto/techdocs/wiki/Tag-your-page-types Apparently, there's no `other` page-type. I've opened an issue and we've added it to our backlog. Thank you.

**Comment by OZZlE** [comment]
@mridang Thanks! Good man! :-)
