### ISSUE TITLE
update API documentation

### ISSUE THREAD

**Issue by KonstantinDerEntwirrer** [Nosto/docs-nosto-com#48]
https://github.com/Nosto/techdocs/wiki/APIs
Add description for Mobile Access API
Unless it is not for the public knowledge

Also is there any documentation on how to use omnichannel api?
What are the differences between omnichannel and apps api?

**Comment by mridang** [comment]
@KonstantinDerEntwirrer Can you be more explicit about what is unclear?

**Comment by KonstantinDerEntwirrer** [comment]
When I was looking up what would be the best way to grant a customer access to using Nosto for his shopify generated mobile app (you know the plugin that converts the website to an app - probably pwa when i think about it now), I came across this documentation to know which API to grant him in our backend. I checked the token types and mobile was not even listed. Since we've had the workshop, I'm sure what to do, but without it was not clear and I assume it will not be for others (clients, agencies, nostonians)

**Comment by mridang** [comment]
This is done.
