### ISSUE TITLE
Product Tagging Categories Unclear!

### ISSUE THREAD

**Issue by OZZlE** [Nosto/docs-nosto-com#49]
You have these examples:

First one has lowercase and no spaces:

    <div class="nosto_product" style="display:none"> 
        <span class="category">/interior</span>
        <span class="category">/interior/towels</span>
    </div>

then you have this image with Camel Case and spaces:
![68747470733a2f2f6e6f73746f2d63616d706169676e2d6173736574732e73332e616d617a6f6e6177732e636f6d2f696d616765732f6e6f73746f2d70726f647563742d74616767696e672e706e67](https://user-images.githubusercontent.com/893783/59192520-fbeaf700-8b82-11e9-8e66-df7d624ef220.png)

Should it be the category name or url path? The first one looks like a relative url path whilst the image looks like category real names separated with slash.

Could you make it more clear in the documentation?

**Comment by mridang** [comment]
@OZZlE I've updated the examples. Sorry about and thank you for reporting the issue.

**Comment by OZZlE** [comment]
@mridang Sorry for being annoying but there is also this :) maybe the examples should be in all lowercase but with spaces in them :) 

![Skärmklipp 2019-06-24 09 47 15](https://user-images.githubusercontent.com/893783/60000761-20f06700-9665-11e9-99a4-e90ed87a4be8.png)
