### ISSUE TITLE
Tracking Nosto with GA

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#52]
Link in question:
https://github.com/Nosto/techdocs/wiki/Tracking-Nosto-with-Google-Analytics#implementation---nosto

How to interpret the documentation on this website correctly?
Am I supposed to code every single part or am I good by setting up both, this
https://github.com/Nosto/techdocs/wiki/Tracking-Nosto-with-Google-Analytics#implementation---nosto ?

and this
https://github.com/Nosto/techdocs/wiki/Tracking-Nosto-with-Google-Analytics#push-product-data-into-productdataforgtm-variable

Or I need to do this as well?
https://github.com/Nosto/techdocs/wiki/Tracking-Nosto-with-Google-Analytics#nosto---tracking-tag

**Comment by mridang** [comment]
This isn't supported.
