### ISSUE TITLE
SPA and Nosto email widget: what has to be done to leverage this feature?

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/docs-nosto-com#54]
- how does the restore cart link work on a SPA? are there differences to a (classic) web shop?
- do I need to adapt parts of the integration such as events or customer data to make all of your three triggers work? all 3 are tied to different circumstances (abandonment, purchase, inactivity)

documentation I am relating too is: https://github.com/Nosto/techdocs/wiki/SPA:-Basics#leveraging-features

**Comment by mridang** [comment]
There is nothing specific about email widgets.
