### ISSUE TITLE
Why are the JSON fields in the API not up to date with the tagging?

### ISSUE THREAD

**Issue by mridang** [Nosto/docs-nosto-com#7]

**Comment by ValterAndersson** [comment]
@mridang can you verify the correct json fields and either fix the article or dump out all the fields we can handle so i can update them? Should be semantically the same as in tagging but i have learned not to assume any kind of standards at Nosto ;) 

We should also correct https://developer.nosto.com/#products

**Comment by mridang** [comment]
Okay, tell me what fields are missing from the API and I'll dig them up.

**Comment by ValterAndersson** [comment]
These are the current fields: 

```
"url"
"categories"
"description"
"product_id"
"name"
"image_url"
"price"
"list_price"
"price_currency_code"
"availability"
"brand"
"tag1"
"tag2"
"tag3"
"date_published" (should probably be removed?)
"thumb_url"
"variation_id"
"variations" (currency, price, availability, list-price)
"google_category" (should this be removed?)
"gtin" (should this be removed?)
"condition" (these examples are a bit confusing)
"age_group" (these examples are a bit confusing)
"gender" (these examples are a bit confusing)
"inventory_level"
"supplier_cost"
"review_count"
"rating_value"
"alternate_image_urls"
```

That means that we are missing how to send basically SKU attributes over the products API and in my opinion the examples in developer.nosto.com and the example article (https://github.com/Nosto/docs-nosto-com/wiki/Updating-products-using-the-Products-API) should be the same set as on https://github.com/Nosto/docs-nosto-com/wiki/Product-Tagging

Who can make changes to developer.nosto.com so it matches our stuff?

**Comment by mridang** [comment]
Updated the wiki
