### ISSUE TITLE
Can I do the templating entirely client-side using your JSON data?

### ISSUE THREAD

**Issue by mridang** [Nosto/docs-nosto-com#9]

**Comment by ValterAndersson** [comment]
We need to decide if we are supposed to also document how to get recommendations showing on the page since this is essentially a feature. Templating again should live in design.nosto.com or someplace like that. 

What are your thoughts @mridang ?

**Comment by mridang** [comment]
I would leave this open until this feature actually works.

**Comment by ValterAndersson** [comment]
I mean we can document how to edit the template, hook on the callback and then render the logic afterwards, but i would also maybe properly document the new API stuff instead when thats done? Lets wait with this.

**Comment by Max93** [comment]
Hi @ValterAndersson any update about JSON feature ?
